name: to_do_list
description: Flutter course assignment

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <=3.0.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  intl: ^0.17.0
  drift: ^1.7.0
  sqlite3_flutter_libs: ^0.5.8
  path_provider: ^2.0.11
  path: ^1.8.0
  shared_preferences: ^2.0.15
  oauth2: ^2.0.0
  flutter_secure_storage: ^5.0.2
  http: ^0.13.4
  url_launcher: ^6.1.4
  uni_links: ^0.5.1
  flash: ^2.0.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  drift_dev: ^1.7.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: ture
  main_locale: en_US
  class_name: Translations
  arb_dir: lib/core/translations/l10n
  output_dir: lib/core/translations/generated
